###
@token = eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsiYWRtaW4tY2F0YWxvZyJdfSwiaWF0IjoxNzQ1MzY3NTU2LCJleHAiOjE3NDU0NTM5NTZ9.G3HcYHyg6W2YiRiDZD7oLCp48YZ_RZV71n74c7hRVd884cG_2NIjkwsoVFvtMDErJw8dONXJ1DK5BiRGdiI1tNT03oC1JV5yuI1YZqfRyEZRt7h3Ny69XC7f9mNLM6Y57XDWiOIUaNz3bifUNr22IASpZQSKVtjgYGVzrrh3-5xCoSaKZf1VRWdiAttUjGY5OjibHVjBOMrH6ptTQrIs0u4RdXlFIZ8LCf0eTUJJYDcltWzRTMZ2ahl1I572gNVHiwVAOfe33iXMl1yzjljI9K269UCwMUt0g2uGDCv4PY2FFSV__NJ_oz64v5Vm7CKZc_3s6QcHZcqQxCbNq65MSw

###
# @name createCategory
POST http://localhost:3000/categories
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Category 1",
    "description": "Description 1"
}

###
@categoryId = {{createCategory.response.body.data.categoryID}}

### Get all categories
GET http://localhost:3000/categories
Content-Type: application/json
Authorization: Bearer {{token}}


### Get category by id
GET http://localhost:3000/categories/{{categoryId}}
Content-Type: application/json
Authorization: Bearer {{token}}
###
# @name createGenre
POST http://localhost:3000/genres
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Genre 1",
    "categoriesId": [
        "{{categoryId}}"
    ]
}

###
@genreId = {{createGenre.response.body.data.genreId}}

###
# @name createCastMember
POST http://localhost:3000/cast-members
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Cast Member 1",
    "type": 1
}

###
@castMemberId = {{createCastMember.response.body.data.castMemberId}}

###
# @name createVideo
POST http://localhost:3000/videos
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "title": "Video 1",
    "description": "Description 1",
    "releasedYear": 2020,
    "isOpened": true,
    "rating": "L",
    "duration": 90,
    "categoriesId": [
        "{{categoryId}}"
    ],
    "genresId": [
        "{{genreId}}"
    ],
    "castMembersId": [
        "{{castMemberId}}"
    ]
}

###
@videoId = {{createVideo.response.body.data.id}}

###
GET http://localhost:3000/videos/{{videoId}}
Content-Type: application/json
Authorization: Bearer {{token}}

###
# @name updateVideo
PATCH  http://localhost:3000/videos/{{videoId}}
###
# @name uploadVideo
PATCH  http://localhost:3000/videos/{{videoId}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="video"; filename="video.mp4"
Content-Type: video/mp4

< ./package.json>
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###
GET http://localhost:3000/fake-event

###
GET http://localhost:3000/rabbitmq-fake

###
POST http://host.docker.internal:8080/realms/codeflix/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

username=admin@user.com
&password=secret
&grant_type=password
&client_id=codeflix-admin-frontend

###
POST http://localhost:3000/auth
Content-Type: application/json

{
    "email": "john@doe.com",
    "password": "123456"
}

###
GET http://localhost:3000/auth
Content-Type: application/json
Authorization: Bearer {{token}}
